routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});



Route::resource('personas/deportistas', 'App\Http\Controllers\DeportistaController')
    ->except(['index', 'show', 'destroy']);

Route::resource('personas/entrenadores', 'App\Http\Controllers\EntrenadorController')
    ->except(['index', 'show', 'destroy'])
    ->parameters([
        'entrenadores' => 'entrenador'
    ]);

Route::resource('personas/referis', 'App\Http\Controllers\ReferiController')
        ->except(['index', 'show', 'destroy']);

Route::resource('personas', 'App\Http\Controllers\PersonaController')
    ->only(['index', 'show', 'destroy']);



Route::resource('deportes', 'App\Http\Controllers\DeporteController')
    ->except(['show']);

Route::resource('equipos', 'App\Http\Controllers\EquipoController');

Route::resource('colegios', 'App\Http\Controllers\ColegioController')
    ->except(['show']);

Route::resource('municipios', 'App\Http\Controllers\MunicipioController')
    ->except(['show']);

Route::resource('torneos', 'App\Http\Controllers\TorneoController');

Route::post('torneos/{torneo}/registrar-equipo', 'App\Http\Controllers\TorneoController@registrarEquipo')
    ->name('torneo.registrarEquipo');

Route::delete('torneos/{torneo}/eliminar-equipo/{equipo}', 'App\Http\Controllers\TorneoController@eliminarEquipo')
    ->name('torneo.eliminarEquipo');

Route::resource('escenarios', 'App\Http\Controllers\EscenarioController');
Route::post('/get-escenarios', 'App\Http\Controllers\EscenarioController@getEscenarios');

Route::resource('patrocinadores', 'App\Http\Controllers\PatrocinadorController')
    ->parameters([
        'patrocinadores' => 'patrocinador'
    ]);

Route::post('patrocinadores/{patrocinador}/sponsor/', 'App\Http\Controllers\PatrocinadorController@sponsor')
    ->name('patrocinadores.sponsor');

Route::delete('patrocinadores/{patrocinador}/unsponsor/{equipo}', 'App\Http\Controllers\PatrocinadorController@unsponsor')
    ->name('patrocinadores.unsponsor');

resources/views/patrocinadores/create.blade.php
@extends('layout.general')
@section('page-title', "Registrar Patrocinador")

@section('page-title-centered', 'Registrar Nuevo Patrocinador')

@section('page-content')

    <div class="create-deportista-form">
        @component('components.form')
            @slot('action', route('patrocinadores.store'))

            @slot('method', "POST")

            @slot('form_content')
                @component('patrocinadores.components.fields')
                @endcomponent

                <div class="row">
                    <div class="col d-grid">
                        <button class="btn btn-primary" type="submit">Registrar</button>
                    </div>
                </div>
            @endslot
        @endcomponent
    </div>

@endsection

resources/views/patrocinadores/edit.blade.php
@extends('layout.general')

@section('page-title', "Editar Patrocinador: $patrocinador->razon_nombre")


@section('page-title-centered', 'Editar Patrocinador')
@section('page-subtitle-centered', "$patrocinador->razon_nombre")


@section('page-content')

    <div class="edit-patrocinador-form">
        @component('components.form')
            @slot('action', route('patrocinadores.update', $patrocinador))

            @slot('method', "POST")

            @slot('fake_method', "PUT")

            @slot('form_content')
                @component('patrocinadores.components.fields')
                    @slot('patrocinador', $patrocinador)
                @endcomponent

                <div class="row">
                    <div class="col d-grid">
                        <button class="btn btn-primary" type="submit">Actualizar</button>
                    </div>
                </div>
            @endslot
        @endcomponent

        <div class="row">
            <div class="col-12 mb-3"></div>
        </div>

        @component('components.form')
            @slot('customAttributes', 'class="d-grid p-0 col"')

            @slot('action', Route('patrocinadores.destroy', $patrocinador))

            @slot('method', "POST")

            @slot('fake_method', "DELETE")

            @slot('form_content')
                <button type="submit" class="btn btn-outline-danger">Eliminar</button>
            @endslot
        @endcomponent
    </div>

@endsection

resources/views/patrocinadores/index.blade.php
@extends('layout.general')

@section('page-title', 'Lista Patrocinadores Registrados')

@section('page-title-centered', 'Lista de patrocinadores registrados')

@section('page-content')

    <div class="row deportes-list-table">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Identificación</th>
                    <th scope="col">Nombre / Razón social</th>
                    <th scope="col">No. Equipos Patrocinados</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach ($patrocinadores as $patrocinador)
                    <tr>
                        <th scope="row"></th>
                        <td>{{ $patrocinador->identificacion }}</td>
                        <td>{{ $patrocinador->razon_nombre }}</td>
                        @if ($patrocinador->patrocinios->count() !== 0)
                            <td>{{ $patrocinador->patrocinios->count() }}</td>
                        @else
                            <td>Ninguno</td>
                        @endif
                        <td><a href="{{ route('patrocinadores.show', $patrocinador) }}" class="btn btn-info">Ir</a></td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

@endsection

resources/views/patrocinadores/show.blade.php
@extends('layout.general')

@section('page-title', "Patrocinador: $patrocinador->razon_nombre")


@section('page-title-centered', 'Información del patrocinador')
@section('page-subtitle-centered', $patrocinador->razon_nombre)


@section('page-content')

    <div class="row patrocinadors-fields-table">
        <table class="table table-striped table-bordered caption-top">
            <caption>Información del patrocinador: {{ $patrocinador->razon_nombre }}</caption>
            <thead>
                <tr>
                    <th scope="col" class="col">Campo</th>
                    <th scope="col" class="col">Valor</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                        <td class="col-md-6">ID:</td>
                        <td class="col">{{ $patrocinador->id }}</td>
                </tr>
                <tr>
                        <td class="col">Nombre / Razón Social:</td>
                        <td class="col">{{ $patrocinador->razon_nombre }}</td>
                </tr>
                <tr>
                    <td class="col">Equipos patrocinados ({{ $patrocinador->patrocinios->count() }}):</td>
                    <td class="col">
                        @if ( $patrocinador->patrocinios->count() !== 0 )
                            <ul>
                                @foreach ($patrocinador->patrocinios as $patrocinio)
                                    <li class="row g-5 py-3">
                                        <span class="d-inline col-auto">{{ $patrocinio->nombre }} (Monto: {{ $patrocinio->pivot->monto }})</span>
                                        <form class="d-inline p-0 col-auto" action="{{ Route('patrocinadores.unsponsor', [$patrocinador, $patrocinio]) }}" method="post">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-outline-danger btn-sm">Eliminar</button>
                                        </form>
                                    </li>
                                @endforeach
                            </ul>
                        @else
                            Ninguno
                        @endif
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="row gap-2">
        <form class="d-grid p-0 col" action="{{ Route('patrocinadores.destroy', $patrocinador) }}" method="post">
            @csrf
            @method('DELETE')
            <button type="submit" class="btn btn-outline-danger">Eliminar</button>
        </form>
        <div class="d-grid p-0 col">
            <a href="{{ Route('patrocinadores.edit', $patrocinador) }}" class="btn btn-outline-primary">Editar</a>
        </div>
    </div>

    <div class="row mt-5 mb-3"><hr></div>

    <div class="row mb-4">
        <div class="col-12">
            <h5 class="text-center">
                Nuevo Patrocinio
            </h5>
        </div>
    </div>

    @component('components.form')
        @slot('action', Route('patrocinadores.sponsor', $patrocinador))

        @slot('method', "POST")

        @slot('customAttributes', "class='row g-3'")

        @slot('form_content')

            <div class="col-auto">
                <label for="" class="col-form-label">Equipo:</label>
            </div>

            <div class="col">
                <select class="form-select" id="equipo_id" name="equipo_id" required>
                    <option selected disabled>Seleccionar Equipo</option>
                    @foreach (\App\Models\Equipo::all() as $equipo)
                        <option value="{{ $equipo->id }}">
                            {{ $equipo->nombre }}
                        </option>
                    @endforeach
                </select>
            </div>


            <div class="col-auto">
                <label for="monto" class="col-form-label">Monto:</label>
            </div>

            <div class="col input-group mb-3">
                <span class="input-group-text">$</span>
                <input type="number" class="form-control" id="monto" name="monto" value="500000" min="500000">
                <span class="input-group-text">.00</span>
            </div>


            <div class="col-auto">
                <button type="submit" class="btn btn-info">Guardar</button>
            </div>


        @endslot
    @endcomponent

@endsection